import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
    title: "Candra Projects",
    description: "Generated by create next",
    icons: "/icon.svg",
    authors: { name: "ItzCandra23", url: "https://github.com/ItzCandra23" },
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <head>
                <link rel="stylesheet" href="https://unpkg.com/boxicons@2.1.4/css/boxicons.min.css" />
            </head>
            <body className={inter.className}>
                {children}
            </body>
        </html>
    );
}
